### PR TITLE
Fix plugins installation for MySQL/MariaDB/SQLite

### LINKED ISSUE #4995: Meshcentral + Plugins
**Describe the bug**
When installing a plugin i get an error "Plugin Error" - "Value is not defined"

**Server Software (please complete the following information):**
 - OS: Debian Bulseeye
 Version: [e.g. 1.1.4]

 - Browser:Chrome&Firefox
 - MeshCentralRouter Version: [if applicable]

**Remote Device (please complete the following information):**
 - Device: Laptop
 - OS: Debian
 - Network: Lan

### PR DESCRIPTION
**Pull request by jrf280**
Fixes #4995

When postgresql it works again I could try to fix too. #5511

Test Plugin: [ https://raw.githubusercontent.com/ryanblenis/MeshCentral-Sample/master/config.json](url)

### CODE REVIEW

**Comment by si458** [comment]
PR #5514 to fix the postgres for you!

**Comment by si458** [comment]
**DO NOT MERGE!**
this will break things for people using postgres as `JSON_INSERT` isnt valid for postgres

**Comment by jrf280** [comment]
This commit dont change any query for postgres.

MySQL/MariaDB : use JSON_INSERT and JSON_MERGE_PATCH
SQLite: use JSON_INSERT and JSON_PATCH

For Postgres  I will use other functions.

**Comment by si458** [comment]
@jrf280 oh sorry, my bad! im having an OFF month so far! yep all looks good!

**Pull request merged**
