### PR TITLE
add docker release action

### PR DESCRIPTION
**Pull request by si458**
EDIT2: all good to go now 17:51 22/07/22

DO NOT MERGE UNTIL YOU HAVE DONE THE FOLLOWING:
1. create a personal access token with `write:packages` and `repo` scopes and an `unlimited` expiration (otherwise you will have to generate a new one every 30 days)
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
2. then add the personal access token to a secret in the repo called `MY_TOKEN`
https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository
3. merge this PR
4. Change package.json version to trigger a new version (this will trigger the automatic release notes, and then trigger the docker build)
5. once the docker image has been built and published (about 15mins), view the package and make it public for others!
https://docs.github.com/en/packages/learn-github-packages/viewing-packages#viewing-your-packages
https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#configuring-visibility-of-container-images-for-your-personal-account

### CODE REVIEW

**Comment by Ylianst** [comment]
Oh wow, interesting!

**Comment by Ylianst** [comment]
I am traveling for the next few days, but this is wonderful. I will work on this ASAP!!!

**Comment by Ylianst** [comment]
Ok, I got the personal token created with the correct rights and the token stored as a secret with exactly the name `MY_TOKEN`. I see what you are doing there, very nice! I am traveling and will not move the version number forward just yet, but next time that happens, I can't wait to see this GitHub action kick in! Thank you!

**Comment by si458** [comment]
@Ylianst from the looks of the actions, it created the docker image and pushed to your packages sucessfully!
however i cant see the package?

did you make the package public?
https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#configuring-visibility-of-container-images-for-your-personal-account

you also might need to link the package to the repo for users to find easier!
https://docs.github.com/en/packages/learn-github-packages/connecting-a-repository-to-a-package#connecting-a-repository-to-a-user-owned-package-on-github

**Comment by Ylianst** [comment]
I just published v1.0.59 and looking into this now. Again, thank you for your guidance on this.

**Comment by Ylianst** [comment]
Just made it public. If you can confirm it all looks good to you, let me know, I will add a link to it.

**Comment by si458** [comment]
> Just made it public. If you can confirm it all looks good to you, let me know, I will add a link to it.

Works a treat now! 
Can you follow issue here and chip in? https://github.com/Ylianst/MeshCentral/pull/4310#issuecomment-1193254144
Just before we update the docs and readme about the new public docker image on github

**Comment by GenuineJakob** [comment]
„Should we include the mongodb by default“
MongoDB 5.X doesn‘t work on the Raspberry Pi 4. If you plan to publish an ARM image/dockerfile, please include mongodb 4.X.

[CopyPaste from mongodb:](https://www.mongodb.com/community/forums/t/core-dump-on-mongodb-5-0-on-rpi-4/115291/13)
MongoDB 5.0 requires ARM v8.2-A or later and the Raspberry Pi 4 uses an [ARM Cortex-A72 2](https://en.wikipedia.org/wiki/ARM_Cortex-A72) which is ARM v8-A.

**Comment by si458** [comment]
@GenuineJakob thanks for your input, currently the dockerfile just installs the monogdb directly from the alpine repo,
so im guessing if it builds an arm version it would install a version thats supported from their repo
im going to test cross-building the images this week as i forgot about arm builds as the current ones are only x64/x86 versions

**Pull request merged**
