### PR TITLE
Docs update on skipmaccheck

### PR DESCRIPTION
**Pull request by silversword411**
Where are all the other .msh options we can add to docs?

### CODE REVIEW

**Comment by si458** [comment]
https://github.com/Ylianst/MeshAgent?tab=readme-ov-file#msh-format

**Comment by silversword411** [comment]
Ok...that's too easy. Think we should just bulk copy/paste that readme into the docs for agent?

**Comment by si458** [comment]
You can also add to the msh file with meshcentral on install too
Screenshot_20240211_134458_Firefox

**Comment by silversword411** [comment]
> meshcentral on install too

Nifty trick. Definitely need to document that :)

**Comment by si458** [comment]
I would maybe add only add the skipmaccheck, as all the others are really just for debug/issues

**Comment by silversword411** [comment]
Stick with that for now. Always add more in the future :)

**Pull request merged**
