### PR TITLE
Bug fix for OIDC Groups

### PR DESCRIPTION
**Pull request by mstrhakr**
I found some issues straight away, if a user was not in a required group it would run a stolen (not present) function from the LDAP section, I replaced it with a bit of code from the 'no new users allowed' section so the code it reports to the login page is wrong.  
Other than that this contains some general cleanup of the debug lines, a check to see if groups are enabled before adding it to the requested OIDC scope, and a small fix to the logic in the filter section so that it will work as expected.

### CODE REVIEW

**Comment by Ylianst** [comment]
Nice!!! FYI. I just put this up on Twitter and will be in my next blog. Let me know if you want changes made, use of your real name, etc.

MC2-OpenID-MembershipGroups

**Comment by Ylianst** [comment]
I will send out MeshCentral v1.0.84 later tonight or tomorrow.

**Comment by mstrhakr** [comment]
Thanks! I love it! I need to get on twitter now lol. I read that you were leaving for vacation and thought, what a great time to start all these pull requests. I hope you enjoy your well deserved break. Thanks again!

**Comment by Ylianst** [comment]
Thanks. Just posted the [latest blog post](https://meshcentral2.blogspot.com/).

**Comment by Ylianst** [comment]
MeshCentral v1.0.84 is out :)

**Pull request merged**
