### PR TITLE
Add dynamic resizing support to xterm.js terminal

### PR DESCRIPTION
**Pull request by TotallyNotElite**
Some notes:

- Only works in PTYs. I couldn't get xterm.js to not do [this](https://user-images.githubusercontent.com/38938720/73110406-90357e80-3f06-11ea-8ee8-8d919883e5fb.png), even without dynamic resizing enabled.
- I removed the following line because it shouldn't even be called when not in terminal mode, + it didn't work for user terminal sessions: `                if (ws.httprequest.protocol == 1) { // Terminal`

Would be great if you could test this first. I tested this on my Manjaro Linux install, but you never know.

### CODE REVIEW

**Comment by krayon007** [comment]
I have 30 VMs of different Linux distros that I can test it on :)

I also added support to child-process.kill to support passing in a signal too, so I can test that at the same time.

**Comment by Ylianst** [comment]
This change is published in MeshCentral v0.4.7-x. I tested it and it does not work on my Raspberry Pi, but does on my old Linux box. However, on my old Linux, if I am in "pico" and resize, it does not work, I have to quit and come back to "pico" and I get the new size.

**Comment by TotallyNotElite** [comment]
Hmm, maybe there's no way around it after all. @Ylianst would it be acceptable to temporarily store the sizes in a file in /tmp? Name would be something like /tmp/mcterminal${pid}

**Comment by krayon007** [comment]
Funny you mention that, as that's actually how I implemented it in my testing.

**Comment by Ylianst** [comment]
Note on this topic. This dynamic resizing code was removed since we are going with a better approach using Kernel support for PTY. It will be in the next agent. Right now, re-size is not supported but this is temporary.

**Pull request merged**
