### PR TITLE
Clean up module install code

### LINKED ISSUE #631: Greenlock install broken
I get the following message:
image
It seems like a timeout of 10 seconds is set, which is WAYYYY too short for npm, especially on low power devices like Raspberry PIs  (I suggest using a timeout of 120 seconds). https://github.com/Ylianst/MeshCentral/blob/338e8eb99e2e027a70bb9843bf9149d4f4872a01/meshcentral.js#L1956
Additionally, MeshCentral doesn't seem to care about the fact that I manually installed the specified version already. (Seems to be buggy because of usage of @ in the package name indicating the version. Works fine for other packages.)

### PR DESCRIPTION
**Pull request by TotallyNotElite**
Did some clean up on the module install code. 

(Merging this PR will auto close #631)

(psst @Ylianst, I wouldn't mind you marking some issues as `good first issue` :+1: )

### CODE REVIEW

**Comment by MailYouLater** [comment]
Careful, currently this PR changes the version number back to one that has already been used.  Please add another commit that fixes this, then use an interactive rebase to squash the fixup into the commit revert commit, and force-push back to your fork to fix this Pull Request.

Also, it's best practice to make your changes on a separate branch on your fork (not `master`) and make your Pull Request from there, because it's easier to keep track of multiple separate patches that way, and it makes it easier to update your fork without messing up a PR.

**Comment by TotallyNotElite** [comment]
Thanks for the advice, but I know how to use git :+1:

**Comment by Ylianst** [comment]
Thanks for this! Your right, my original change was a hack until I get back. FYI. I am in South Australia right now, pretty much as far form home as I could be. I really appreciate the help with this pull request.

**Comment by MailYouLater** [comment]
> Thanks for the advice, but I know how to use git 👍

But you amended the wrong commit. ☹️ If you'd done what I said, then the git history would show reverting the code changes without changing the version number, but now the main repo has two commits that change the version number back to a version that was already used (first to v, then to w).  This is very bad form, some projects automatically publish an update based on a new version number, and changing the version number to a previously used version can cause them major issues.

**Comment by TotallyNotElite** [comment]
Some projects do do that, but it's important to note that the pipeline wouldn't even run on the first commit in the first place. Also, I'm not a big fan of amending revert/merge commits in general.

**Comment by MailYouLater** [comment]
Depends on what they're using for CI, and how it's set up.
Whatever, what's done is done, the important part is that the fix is in. 👍

**Pull request merged**
