### PR TITLE
added optional build arguments to disable minification/translation

### PR DESCRIPTION
**Pull request by sschoen**

### CODE REVIEW

**Comment by Ylianst** [comment]
You are on a roll!

**Comment by si458** [comment]
the build args arent working for some reason
```
simon@docker:~/MeshCentral$ docker build -f docker/Dockerfile --force-rm --build-arg DISABLE_MINIFY=yes --build-arg DISABLE_TRANSLATE=yes --no-cache -t si458/meshcentral:1.0.34 .
Sending build context to Docker daemon  147.2MB
Step 1/29 : FROM node:current-alpine AS base
 ---> c4f3fb5f722f
Step 2/29 : RUN mkdir -p /opt/meshcentral
 ---> Running in 48a57cb3bbef
Removing intermediate container 48a57cb3bbef
 ---> fb393844f3fe
Step 3/29 : WORKDIR /opt/meshcentral
 ---> Running in d98559ff076d
Removing intermediate container d98559ff076d
 ---> c5506cb75ef3
Step 4/29 : RUN apk add --no-cache bash
 ---> Running in 91080bdd0fd7
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
(1/4) Installing ncurses-terminfo-base (6.3_p20220521-r0)
(2/4) Installing ncurses-libs (6.3_p20220521-r0)
(3/4) Installing readline (8.1.2-r0)
(4/4) Installing bash (5.1.16-r2)
Executing bash-5.1.16-r2.post-install
Executing busybox-1.35.0-r13.trigger
OK: 10 MiB in 20 packages
Removing intermediate container 91080bdd0fd7
 ---> 9d4057c2b7f6
Step 5/29 : FROM base AS builder
 ---> 9d4057c2b7f6
Step 6/29 : ARG DISABLE_TRANSLATE=""
 ---> Running in 3a518f9922c5
Removing intermediate container 3a518f9922c5
 ---> 77cbebb27d05
Step 7/29 : ARG DISABLE_MINIFY=""
 ---> Running in d1d8a65c31b2
Removing intermediate container d1d8a65c31b2
 ---> 3d01af0860a7
Step 8/29 : RUN mkdir /opt/meshcentral/meshcentral
 ---> Running in 1a5606040e91
Removing intermediate container 1a5606040e91
 ---> 36a451c92f4f
Step 9/29 : COPY ./ /opt/meshcentral/meshcentral/
 ---> 15e75ba4865b
Step 10/29 : RUN cd meshcentral/translate && node translate.js extractall; exit 0;
 ---> Running in e3dc79259b6b
Installing jsdom...
^C
```

**Comment by si458** [comment]
https://github.com/Ylianst/MeshCentral/blob/master/docker/Dockerfile#L21-L22

@sschoen the 2 extract lines arent required because the translate.json is already included from the word go,
its only needed if you wanted to translate files (again i dont need it only english)

**Comment by sschoen** [comment]
@si458 https://github.com/sschoen/MeshCentral/tree/Bugfix/docker

**Comment by si458** [comment]
> @si458 https://github.com/sschoen/MeshCentral/tree/Bugfix/docker

Bingo thank you!

**Pull request merged**
