### PR TITLE
Feature Request: Generic OIDC

### PR DESCRIPTION
**Pull request by mstrhakr**
I've build my own feature :) 
I hope this is good enough, I would LOVE to be able to say I've contributed to an open source project.
I managed to publish my version of the openid connect passport module to npm @mstrhakr/passport-generic-oidc and have pointed everything in MeshCentral to grab that one vs the one I was using for testing originally.
#3814 for reference

### CODE REVIEW

**Comment by Ylianst** [comment]
Thank you! Looks great. This will be in MeshCentral v1.0.3.

**Comment by bodycount28** [comment]
I'm also interested in integrating with Authelia, using it with Traefik.

@mstrhakr - Assuming it's set up, would you mind sharing your settings/parameters in both Authelia and Meshcentral configs?

BTW - thanks for the great work, both of you...

**Comment by mstrhakr** [comment]
@Ylianst if you want to incorporate these into the docs somewhere that would be cool with me. I could attempt a few other generic oidc setups and gather configs for those too if there is any specific interest.

**Comment by bodycount28** [comment]
@mstrhakr - Thanks for sharing.  I just tried implementing, however MC gave an error after logging in via OIDC...

`Error: id token not issued by correct OpenID provider - expected: https://auth.my.domain:443 | from: https://auth.my.domain
    at /home/node/meshcentral/node_modules/@mstrhakr/passport-generic-oidc/lib/strategy.js:151:15
    at /home/node/meshcentral/node_modules/oauth/lib/oauth2.js:209:7
    at passBackControl (/home/node/meshcentral/node_modules/oauth/lib/oauth2.js:134:9)
    at IncomingMessage.<anonymous> (/home/node/meshcentral/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)`

Any thoughts?

**Comment by mstrhakr** [comment]
Needs the port number, had the same issues with my original testing. In my example that item has a :443 at the end.

**Comment by bodycount28** [comment]
I got it working.  I wound up having to remove port :443 from the end of the issuer url.  Thanks again!

**Comment by archef2000** [comment]
I setup MeshCentral with Authelia using the config above with/without authorization, toke, user URL but i get this error message after i click Allow on the authelia page and meschcentral restarts after 5 seconds:

```
Error: Command failed: /usr/local/bin/node /opt/meshcentral/node_modules/meshcentral --launch 8

/opt/meshcentral/node_modules/passport/lib/middleware/authenticate.js:134

          req.flash(type, msg);

              ^

TypeError: req.flash is not a function

    at allFailed (/opt/meshcentral/node_modules/passport/lib/middleware/authenticate.js:134:15)

    at attempt (/opt/meshcentral/node_modules/passport/lib/middleware/authenticate.js:183:28)

    at strategy.fail (/opt/meshcentral/node_modules/passport/lib/middleware/authenticate.js:305:9)

    at /opt/meshcentral/node_modules/@mstrhakr/passport-openidconnect/lib/strategy.js:171:56

    at /opt/meshcentral/node_modules/oauth/lib/oauth2.js:209:7

    at passBackControl (/opt/meshcentral/node_modules/oauth/lib/oauth2.js:134:9)

    at IncomingMessage.<anonymous> (/opt/meshcentral/node_modules/oauth/lib/oauth2.js:157:7)

    at IncomingMessage.emit (node:events:525:35)

    at endReadableNT (node:internal/streams/readable:1359:12)
ERROR: MeshCentral failed with critical error, check mesherrors.txt. Restarting in 5 seconds...
```

**Comment by KDima23** [comment]
I have the same issue  as @archef2000.
Is there are some fix for it?
@mstrhakr and @Ylianst

**Pull request merged**
