### PR TITLE
Dutch language update 1.1.21

### PR DESCRIPTION
**Pull request by petervanv**
NOTE: i saw a lot off undefined strings, please review

example: [[[SERVERNAME]]] - Account Invitation\nAn account was created for you on server [[[SERVERNAME]]] ([[[SERVERURL]]]/[[[URLARGS1]]]), you can access it now with username "[[[ACCOUNTNAME]]]" and password "[[[PASSWORD]]]".\n~\nBest regards,\n~[[[USERNAME]]]

### CODE REVIEW

**Comment by si458** [comment]
All looks good to me thanks!
The strings u added are all new ones I've added recently so they should be translated now correctly!

**Comment by petervanv** [comment]
what I mean is this, a piece of text, which is not translated, but also has no function in meshcentral. the location is not filled in (xloc info)

image
image

**Comment by si458** [comment]
yes thats prefectly fine, i spotted this while i was fixing translations, 
its basically OLD text from older versions, which might of been removed in newer versions but not removed from the translate.json,
you will only see xloc IF its found the string somewhere in the txt files or handlebar files!

**Comment by petervanv** [comment]
Maybe an good idea too clean it up ? if it aint nessesary (some parts, are double's)

**Comment by si458** [comment]
@petervanv have a look then, checkout the recent translate.json and see what you can find,
i did a full extract the other day so all strings should be up to date

**Comment by petervanv** [comment]
#5871

**Pull request merged**
