### PR TITLE
 added fix to hande process.env.LANG = "C" 

### PR DESCRIPTION
**Pull request by reddn**
When the environment process does not have a language set, it defaults to "C". This PR changes the language to English and sends a console log about how to find and specify the language for translation.

Without this, the it will set the language to lowercase "C" which is not found in agent-translations.json, which throws an error on install "Language: c is not translated" and exits.

### CODE REVIEW

**Comment by reddn** [comment]
I guess the mysterious util-langauge package just returns process.env.LANG (at least on node 18+).  This defaulted to "C" on my raspberry pi, which obviously will cause an issue as the code current expects util-language.current to return 'null' if there is no locale setting.  

The current code looked for a 'c' in the agents-translation.json file, which there is none, which causes the error in issue https://github.com/Ylianst/MeshCentral/issues/4061 4061.

**Comment by reddn** [comment]
Here is what the raspberry pi showed under 'process.env'

`> process.env
{
  HISTCONTROL: 'ignoreboth',
  EDITOR: 'vim',
  PWD: '/root',
  QT_QPA_PLATFORMTHEME: 'qt5ct',
  LINES: '42',
  LANG: 'C',

  LS_COLORS: **removed**
  COLUMNS: '91',
  PROMPT_COMMAND: 'PS1="[$(prompt_user)@$(prompt_host)$(prompt_git)]$(prompt) "',
  TERM: 'xterm-256color',
  SHLVL: '1',
  PAGER: 'less',
  PATH: '/usr/local/sbin:/usr/local/bin:/usr/bin:/sbin',
  OLDPWD: '/usr/local/mesh_services/meshagent',
  _: '/usr/bin/node'
}
`

My other computer where the error did not occur showed this 
`> process.env.LANG
'en_US.UTF-8'`

**Comment by reddn** [comment]
Would it be better to make it where if process.env.LANG does not match a language in the agent-translator.json (file name might not be correct) that it should give a error in console and default to 'en'?

This would make it where no matter what crap you send to it as a set language, it will still run and not fail.

**Comment by krayon007** [comment]
For giggles, can you run the following three commands on your system that is showing "C"?
`./meshagent -exec "console.log(require('user-sessions').gdmUid);process.exit();"`

That will show the UID of the GDM on the system.... Then using that, run the following command, substituting 114 with the UID from above:
`ps -e -o pid -o uid | grep 114`

Then using the returned PID, run the following command, substituting 1562 with the PID from above
`./meshagent -exec "console.log(require('user-sessions').getEnvFromPid(1562));process.exit();"`

I'm curious if the above command has the correct language setting. It is basically fetching it from the environment of the GDM. This method is what I normally try to do if the language setting in the agent's process isn't set. In your case, the agent's environment's lang is set to "C".

**Comment by reddn** [comment]
```
[root@pikvm root]# ./meshagent -exec "console.log(require('user-sessions').getEnvFromPid(16969));process.exit();"

{ LANG: C, PATH: /usr/local/sbin:/usr/local/bin:/usr/bin, INVOCATION_ID: 57e9c73fcb0345de846cc66ebb05d817, SYSTEMD_EXEC_PID: 16969 }
[root@pikvm root]# ps -aux | grep mesh
root     15688  0.0  0.0   2920  1188 pts/4    S+   15:45   0:00 grep --color=auto mesh
root     16969  0.0  0.6  23172 12984 ?        Ss   Jun01   0:30 /usr/local/mesh_services/meshagent/meshagent --installedByUser=0
[root@pikvm root]# 
```

**Comment by reddn** [comment]
The first command didnt work on it 

```[root@pikvm root]# ./meshagent -exec "console.log(require('user-sessions').gdmUid);process.exit();"

0
[root@pikvm root]# ```

but I just did `ps -aux | grep mesh` to the the pid of the mesh agent

**Comment by krayon007** [comment]
What display manager are you running? It's actually the pid of your display manager I was interested in. If you check your passwd file you should be able to find the uid of your display manager.

**Comment by reddn** [comment]
No display manager.  Its a headless raspberry pi running PI KVM

**Comment by reddn** [comment]
based on arch

**Comment by reddn** [comment]
Did some digging.. my Ubuntu 18.04 LTS headless has it set correctly (under
/etc/default/locale), but on this raspberry pi, based on arch, has the file
/etc/locale.conf which has "LANG=C".

Instead of making "C" default to 'en', I think it would be better to make
it default to 'en' if the specified locale language does not meet the list
already in agent_translations.json.  Let meknow if you want me to do that
and I'll take out my 'workaround' (if LANG = C) as the workaround doesnt
catch any other dumb LANG configuration that does not match a langauge.

**Pull request merged**
