### PR TITLE
disconnect sessions first before logout on idletimeout

### LINKED ISSUE #5820: Desktop connection is not automatically disconnected upon idle timeout
**Describe the bug**
with "userSessionIdleTimeout" in the Config file, when using the Desktop to connect to another device, the browser is prompting  a confirmation request for leaving or staying in the site.
This is true to the Desktop and not the RDP as I didn't test it on RDP.

**To Reproduce**
1. Add "userSessionIdleTimeout to the Config file
2. Connect to a device using the Desktop
3. Leave the connect until idle
4. See prompt from the browser

**Expected behavior**
Disconnecting the Desktop connection upon idle timeout

**Screenshots**

**Server Software (please complete the following information):**
 - OS: Linux Mint
 - Version: 1.1.21
 - Node: v20.11.1

**Client Device (please complete the following information):**
 - Device: Laptop and Tower
 - OS: Window 11 and Linux Mint 21.3
 - Network: Local and Remote
 - Browser: Firefox (Tested as well in Edge)

**Remote Device (please complete the following information):**
 - Device: Laptop and Tower
 - OS:Window 11 and Linux Mint 21.3
 - Network: Local and Remote
 - Current Core Version (if known): Nov 21 2022, 2089848313 (Linux) Dec 9 2022, 1508625241 (Windows)

**Additional context**

**Your config.json file**
```
{
  "$schema": "https://raw.githubusercontent.com/Ylianst/MeshCentral/master/meshcentral-config-schema.json",
"__comment1__": "This is a simple configuration file, all values and sections that start with underscore (_) are ignored. Edit a section and remove the _ in front of the name. Refer to the user's guide for details.",
  "__comment2__": "See node_modules/meshcentral/sample-config-advanced.json for a more advanced example.",
  "settings": {
    "cert": "91.65.173.11"
  },
  "domains": {
    "": {
	"userSessionIdleTimeout": 15
    }
  }
}

### PR DESCRIPTION
**Pull request by si458**
Fixes #5820

Signed-off-by: si458 <simonsmith5521@gmail.com>

### CODE REVIEW

**Comment by quizhead** [comment]
Thanks a lot.
Should I do something or wait?

**Comment by si458** [comment]
if your desperate (hehe),
you can use the docker `master` image
OR
copy and paste the master `default.handlebars` file and restart meshcentral! https://github.com/Ylianst/MeshCentral/blob/master/views/default.handlebars

**Comment by quizhead** [comment]
An opportunity to learn something new.
Where do I find the default.handlebars in the server?

**Comment by si458** [comment]
you then simply download the file from above, and cut+paste (overwrite) the file in `node_modules/meshcentral/views/default.handlebars`

**Comment by quizhead** [comment]
Opportunity to learn something new.
I've found the path 2 seconds after asking.
Never thought a simple search can find it.
Testing and reporting back.

**Comment by quizhead** [comment]
Ok tested and still getting the browser prompt.
Sorry to disappoint.

**Pull request merged**
