### PR TITLE
Update default.handlebars

### PR DESCRIPTION
**Pull request by smartekIT**
Fix Toggle Star limit of 20 to make it 200

### CODE REVIEW

**Comment by smartekIT** [comment]
https://github.com/Ylianst/MeshCentral/issues/5128

**Comment by silversword411** [comment]
Looks like you linted/reformatted the file, you should only change the lines you want

**Comment by smartekIT** [comment]
> Looks like you linted/reformatted the file, you should only change the lines you want

did I ?!
I just changed one figure in one line (20 changed to 200) that's all.

**Comment by si458** [comment]
yeh that seems like a HUGE commit if you only changed 1 line, 
ive checked your repo and the commits the same 38000 line changes instead of 1

**Comment by smartekIT** [comment]
not sure what happened, I guess I should cancel the pull then start over if it causing this much trouble!
what you think?

**Comment by si458** [comment]
fixed for you #5133 so you can close this PR, thanks for finding the fix tho!

**Pull request closed without merging**
