### PR TITLE
Check on nedb usage and node >=23

### PR DESCRIPTION
**Pull request by PTR-inc**
'fixes' #6503

### CODE REVIEW

**Comment by si458** [comment]
I have spoken with @Ylianst he wants to keep nedb!
So we are gunna look for another nedb fork that is newer and works with v23 then move to that instead

**Comment by si458** [comment]
If we implemented this PR it would break all existing setups so hense we looking for another module instead 

But also we should inform the user they can use `--nedbtodb` to migrate there existing nedb to any db they setup

**Comment by PTR-inc** [comment]
Maybe already put a deprecation inform/warning in the current version, as a server message?

I quickchecked the original nedb btw and at first glance it doesn't seem like a very big job to fix the deprecated util functions.

**Comment by si458** [comment]
@PTR-inc agreed it looks like a simple fix from the forked repo we use, but there is other repositorys that replaces the `util` completely, which might be more ideal!

Maybe a warning to tell others to move to a different database but will ask @Ylianst

**Comment by PTR-inc** [comment]
If somebody already did it, better ofcourse! Which ones are you looking at?

**Comment by PTR-inc** [comment]
Added the warning. Just for completeness. Do you want to replace the module before the next release?

**Comment by si458** [comment]
@PTR-inc I will speak with @Ylianst and ask his opinion as curre try this pr would stop it working all together, as u have removed the nedb module and also out the warning, let me come bk to u

**Comment by PTR-inc** [comment]
@si458 Node 23 errors out if the current nedb module is used, so exitting gracefully if trying to use nedb seemed like the nicer option to offer with a clear message. But a replacement module would be better for sure.

**Comment by si458** [comment]
closing as we have used a newer module which supports node 23 now 👍

**Pull request closed without merging**
