### PR TITLE
German Translation for MeshCentral #765

### PR DESCRIPTION
**Pull request by veitw**
* all missing German translations added
* some existing German translations improved
* translation update performed using current RessourceTranslator, causing a re-sort of the translate.json file for language id

### CODE REVIEW

**Comment by veitw** [comment]
German translation update no. 3  to #765

**Comment by Ylianst** [comment]
Thanks. Looks like it's working correctly. This will be in MeshCentral v0.5.10 later today. Thank you!!!

**Comment by veitw** [comment]
Always glad to help.

Hope y'all are well!

**Comment by Ylianst** [comment]
MeshCentral v0.5.10 is published! Let me know if there are any issues.

**Pull request merged**
