### PR TITLE
removed .git folder from docker image (significant size improvement)

### PR DESCRIPTION
**Pull request by sschoen**

### CODE REVIEW

**Comment by si458** [comment]
1. the pr does indeed shrink it down from my 606mb build to 587mb (no mongodb included)
2. it still takes over 5 mins to build because of the minify/translate
3. if i remove the lines for minify/translate it will shrink it down further to 346mb, so im confused why minify would increase the build in size?

**Comment by si458** [comment]
@Ylianst this PR wasn't ready for merge, we are still working out the kinks for you, sorry

**Comment by sschoen** [comment]
@si458 https://github.com/sschoen/MeshCentral/tree/Feature/docker
you can disable translation/minification by adding the "DISABLE_MINIFY=yes" and/or "DISABLE_TRANSLATE=yes" build arguments...


> docker build -f docker/Dockerfile --force-rm --no-cache --build-arg DISABLE_MINIFY=yes --build-arg DISABLE_TRANSLATE=yes -t meshcentral .

"Size": 468693122

> docker build -f docker/Dockerfile --force-rm --no-cache --build-arg DISABLE_TRANSLATE=yes -t meshcentral .

"Size": 470010833

> docker build -f docker/Dockerfile --force-rm --no-cache --build-arg DISABLE_MINIFY=yes -t meshcentral .

"Size": 536570405

> docker build -f docker/Dockerfile --force-rm --no-cache -t meshcentral .

"Size": 537888268

**Comment by si458** [comment]
@sschoen that's just about perfect!
Could you maybe add in `if not true` to the checks?
Just Incase people use true instead of yes

**Comment by sschoen** [comment]
thats not necessary, i added the build args to the readme.md...

### Optional build arguments
> | Argument                | Description                                         |
> | :---                    | :---                                                |
> | INCLUDE_MONGOTOOLS=yes  | Includes mongodb-tools (mongodump, ...) in the image |
> | DISABLE_MINIFY=yes      | Disables the minification of files                  |
> | DISABLE_TRANSLATE=yes   | Disables the translation of files                   |

**Pull request merged**
