### PR TITLE
Google Workspace OAuth2 SMTP Documentation

### PR DESCRIPTION
**Pull request by buckybytes**

### CODE REVIEW

**Comment by buckybytes** [comment]
Accidental PR, but might as well preserve it while I work.

**Comment by buckybytes** [comment]
I made an attempt to keep things pretty general, in hopes that as Google slowly changes the process, the documentation at least remains a good enough hint to get the job done.

**Comment by si458** [comment]
You have forgotten to commit the images

**Comment by silversword411** [comment]
As it stands right now the only thing this PR does is move the Email setup section to above the Database section. Am I missing something else?

**Comment by buckybytes** [comment]
I've got a problem with my workflow somewhere.  I think I need to abandon the thought of using GitHub's web interface for anything, and just stick to the CLI.

I've re-committed both the images and the update to the index.md

**Comment by adnan29979** [comment]
Great work on the documentation, @buckybytes. While reviewing, I came across a detail that seems to require correction. It appears we don't have a field named "accessToken" in the `config.json` file. I checked the source code `meshmail.js` as well (please double-check in case I missed it in the source code). Aside from this point, the documentation for `config.json` looks accurate and comprehensive.

**Comment by si458** [comment]
@adnan29979 I have merged this, so u can now pull and submit a pr with any fixes!

**Pull request merged**
