### PR TITLE
Use PTY if python is available

### PR DESCRIPTION
**Pull request by TotallyNotElite**
Currently, using the terminal functionality will only make the current shell interactive. This means that sub-shells will not have the usual "$" or other values for $PS1, CTRL+C will kill any sub-shells created and backspace and other special key combinations won't work correctly.

This issue occurs whenever a sub-shell is started, including switching users (which is very bad because of the above mentioned problems). Using a PTY fixes this problem completely, by making programs (like bash) think they're running in an interactive terminal.

(PS: I spent a lot of time figuring this out because its REALLY frustrating and DESTROYS the user experience)

### CODE REVIEW

**Comment by TotallyNotElite** [comment]
Before: image
After: image

**Comment by TotallyNotElite** [comment]
Looks like the `.min.js` has to be updated too, but I don't understand the difference between the files. There are only minor changes related to "wallpaper" in there. I guess I'll just copy the file over?

**Comment by krayon007** [comment]
The .min one was run thru a minifier to reduce the size of the file. I usually only update the non minified one because ylian runs a script when he publishes that minifies the thing automatically or something like that.

**Comment by TotallyNotElite** [comment]
> The .min one was run thru a minifier to reduce the size of the file. I usually only update the non minified one because ylian runs a script when he publishes that minifies the thing automatically or something like that.

Ah! Thanks for the clarification! If that's the case, it doesn't really serve any purpose. Maybe removing it is a good idea to stop confusion in the future :thinking:

**Comment by krayon007** [comment]
Yeah, when I do testing, I just delete the minified version from my test server. Then the server will just serve the regular version. Same with the agents. I delete the signed ones from the server, so it'll serve the non signed test version.

**Comment by Ylianst** [comment]
Nice work! I am certainly accepting this. If someone can figure out a way to do this without Python that would be even better, but this great.

**Pull request merged**
