### PR TITLE
Update chart js to 4.3.3

### LINKED ISSUE #5275: Update ua-parser-js and chart-js - critical CVEs
**Describe the bug**
Hello @Ylianst the dependencies or cross-deps have major CVE reports, please update the deps and release a "clean" version. Current Version is 1.1.8.

**To Reproduce**
Do a SBOM scan on this package via Sonatype Nexus

**Expected behavior**
Removal of CVEs through updating assets

**Screenshots**
image

### PR DESCRIPTION
**Pull request by si458**
Fixes #5275 
this will update chartjs to 4.3.3, this now requires an adapter and moment.js
sadly we have lost the shadoweffect on the doughnuts
but i will work out how to add them back in the future

### CODE REVIEW

**Comment by jammsen** [comment]
@Ylianst Do you have an eta when do you have time to review this? 
I would like to security scan the next release.

**Comment by jammsen** [comment]
@Ylianst please review and merge this, we need this to get this the CVE out of the software and to prevent Virus-Scanners to quarantine this. I tried my best to help out here, but we are now waiting 3 weeks for you and we really need this fix in the software to actually use it.

**Comment by Ylianst** [comment]
So sorry for the delay on this. I am going to give my phone number to @si458 so I can do security checking and accept this faster. I will be releasing a new version of MeshCentral tomorrow.

**Comment by jammsen** [comment]
Thank you very much

**Pull request merged**
