### PR TITLE
Plugin Extensibility

### PR DESCRIPTION
**Pull request by ryanblenis**
While attempting to get familiar with the project I've added a modular plugin based system to the base, along with a sample plugin to go along with it: [MeshCentral-EventLog](https://github.com/ryanblenis/MeshCentral-EventLog).
The design of this implementation allows developers to modify back end, front end, and MeshAgent hooks to allow a wide range of flexibility for the plugin developer. The changes also create an easy method for future "hooks" to be added to the core MeshCentral project via the `callHook` method.

I believe this could help many people extend MeshCentral with their own additions that the MeshCentral developers may or may not see as part of the core mission of MeshCentral.

### CODE REVIEW

**Comment by jsastriawan** [comment]
It is a nice concept. It looks like you implement agent code insertion, server logic handling and console display. And the beauty of your implementation is that this plugin resides on meshcentral-data. I will look at that.

**Comment by Ylianst** [comment]
Lots of things here, it's going to take me a little time to check everything. I need to make sure everything is secure, etc.

**Comment by ryanblenis** [comment]
Fantastic! I've published a sample plugin at https://github.com/ryanblenis/MeshCentral-EventLog

**Comment by Ylianst** [comment]
Thanks. I will take a look at it. Don't hesitate to submit more fixes if needed.

**Pull request merged**
