### PR TITLE
Migrate existing OpenID Connect strategy to openid-client.

### PR DESCRIPTION
**Pull request by mstrhakr**
This should be ready to look at now. I've squashed most of the bugs and cleaned up my mistakes, even wrote some documentation I just need someone else to give it a look. As I normally do, I've made a docker image available to anyone interested in testing these features themselves.

Docker Image :`mstrhakr/meshcentral:dev`
Build Command: `docker build -f docker/Dockerfile --force-rm --build-arg DISABLE_MINIFY=yes --build-arg DISABLE_TRANSLATE=yes -t mstrhakr/meshcentral:dev .`

# Documentation

## Overview

- [x] Introduction
- [x] Definitions
- [x] Terms

## Configuration

- [x] Basic Config

### Advanced Config 

- [x] Issuer
- [x] Client
- [x] Custom
- [x] Groups

### Presets Config

- [x] Azure
- [x] Google

### Old Configs

- [x] Basic
- [x] Advanced
- [x] Presets
- [x] Upgrading to this version

### *original post below*

This is working, but I have not done enough testing to say it is merge ready, I can all but guarantee there will be more commits.

Not to mention until @Ylianst returns I assume this can't/shouldn't be merged. I'm only putting it here so anyone who is interested can inspect this for issues or comment on how things should be setup. 

I passed through all of the potential options for openid-client's `Client` and `Issuer` classes through to the config file so the schema for oidc has grown by an order of magnitude. I figured we give the power to the people.

I've also set it up so existing configs will be parsed correctly, although the new config style is preferred. (Now that I mention it, I should rearrange things so the new config options override the old ones if both are set.)

### CODE REVIEW

**Comment by mstrhakr** [comment]
This is a major upgrade to SSO on MeshCentral that will allow group support for any previously OAuth2.0 IdP's that support it among other things. Hopefully the way I went about it is okay. Now I just need to do a bunch of testing with azure, google, and all the other preset options.
This is still a work in progress but I've made some great progress.

**Comment by Ylianst** [comment]
Oh dear. Indeed, a quick look at this, it's clear this would cause all existing servers setup with these authentication techniques to stop working when updating. What I would like if to keep the existing code but create a new config.json key for this feature.

**Comment by mstrhakr** [comment]
> Oh dear. 
Yea.. This isn't even close to ready yet. My goal is to have this be ready for review shortly before you return. I wouldn't look _too_ close in the meantime.

> Indeed, a quick look at this, it's clear this would cause all existing servers setup with these authentication techniques to stop working when updating. 
I have Azure working now, but I still need to go through the rest of the strategies and test them, but the worst is behind me at this point.

> What I would like is to keep the existing code but create a new config.json key for this feature.
I've got it setup in such a way that all (only works for oidc and azure so far) the old configs  are imported and setup automatically.

I even figured out how to update the userid for azure users by cloning the user, remaking the db entry, then deleting the original user. I'm still working out what issues this could cause but I'm not there yet.

I really appreciate you taking time from your vacation to review this, but again, I don't consider this ready for review quite yet. Once I'm done, you should be able to merge this without worrying about issues from an update.

**Comment by mstrhakr** [comment]
> What I would like if to keep the existing code but create a new config.json key for this feature.

I removed all the changes I made to the other strategies. Hopefully this looks okay, I tested it with a bunch of different combinations of configs. The only untested feature at the moment is groups for the azure and google presets, they worked once but I haven't fully tested that again since all these changes.

**Comment by mstrhakr** [comment]
Code is finally feature complete (for now), just needs a few more rounds of testing.
Here's a rough layout of the documentation I plan on writing before marking this as ready.

# Configuration
- [ ] Issuer
- [ ] Client
- [ ] Options
- [ ] Custom
- [ ] Old Configs
# User Attributes
- [ ] User ID
- [ ] Email and Verification
- [ ] Groups Scope/Claim
# Migration
- [ ] Old Configs
- [ ] Google
- [ ] Azure
# Presets
- [ ] Google
- [ ] Azure
# Groups
- [ ] Required
- [ ] Site Admin
- [ ] Sync / Filter
- [ ] Scope / Claim

**Comment by mstrhakr** [comment]
@Ylianst This is ready for you to look at whenever. If you want any work done before merging let me know. I'm more than happy to clean up my own messes.

**Comment by Ylianst** [comment]
I will close this one since it's older and somewhat risky to add. If you really want this, open a new PR and I will look at it again. My worry with this one is that it will break existing installations.

**Pull request closed without merging**
