### PR TITLE
Doc update - Addition of 'How to Contribute' section

### PR DESCRIPTION
**Pull request by adnan29979**
- A new 'how to contribute' section in documentation.
  - It has a "Contributing to MeshCentral via GitHub Pull Request" section.
  - and a "Contribute to MeshCentral's Multilingual Support" section.
  - This is a live sample (https://adnan29979.github.io/MeshCentral/how-to-contribute/). Please visit this to see the necessary changes and see the formatting and other previews of the 'how-to-contribute' page if necessary.

### CODE REVIEW

**Comment by si458** [comment]
its not as simple as adding a language to the translator tool as you need to also add it into meshcentral so its aware of the language

please can you remove that?

ill happily accept the docs update tho! thank you for this!

**Comment by adnan29979** [comment]
Aight. No worries. removed that. 

I tested that initially and it worked btw. the translate.json was being generated properly with 'bn' field added to it.

**Comment by si458** [comment]
absolute legend thank you!
docs where never my expertience!
im still looking at the languages for you, as we also have the `translate tool` which would need updating,
but i have no sourcecode for this so need to ask @Ylianst for it

**Comment by adnan29979** [comment]
Welcome, brother. 
Bro, you're the literal legend here. I'm just the one with the docs. haha. 
Aight no worries with that 🚀 
Thanks for taking a look into them 🚀🚀

**Pull request merged**
