### PR TITLE
Various (linux) terminal improvements

### PR DESCRIPTION
**Pull request by TotallyNotElite**
- (not terminal related) Fix "undefined" when downloading a backup
- Don't store automatic commands in the bash history
- Refactor terminal setup code
- Create interactive terminals without python (see #677) [;)](https://github.com/Ylianst/MeshCentral/pull/677#issuecomment-558259078)

### CODE REVIEW

**Comment by TotallyNotElite** [comment]
Also, interesting how the agent doesn't support backticks (`).

**Comment by Ylianst** [comment]
Thanks. Accepted and published in MeshCentral v0.4.6-j. Note that changes to meshcore.min.js don't count since I re-generate that file from meshcore.js. You can delete the "meshcore.min.js" from your server and "meshcore.js" will automatically be used, then edit that file.

**Comment by TotallyNotElite** [comment]
Maybe you should consider removing it from the source code altogether.

**Comment by MailYouLater** [comment]
You could add it to `.gitignore` to prevent git from trying to re-add it later.

**Comment by Ylianst** [comment]
Arg. I should not have accepted this pull request as it broke the terminal on [MacOS and many Linux distros](https://github.com/Ylianst/MeshCentral/issues/755). Bryan fixed the issues and it's now in MeshCentral v0.4.6-k.

**Comment by Ylianst** [comment]
@MailYouLater I just did it, added the auto generated files to .gitignore and removed them from GitHub. That was a good move, cleaned up source control a bunch.

**Comment by MailYouLater** [comment]
Yeah, it's too bad it wasn't caught and fixed while it was just a PR, but at least it was caught and fixed quickly afterwards.  It's really nice how responsive and quick to fix issues you and your team are.  Good job guys!

**Comment by TotallyNotElite** [comment]
Interesting. I thought `script`'s functionality was universal. Great that this was fixed tho.

**Pull request merged**
