### PR TITLE
add no consent to guest sharing

### PR DESCRIPTION
**Pull request by si458**
Fixes https://github.com/Ylianst/MeshCentral/issues/5341

Signed-off-by: si458 <simonsmith5521@gmail.com>

### CODE REVIEW

**Comment by exander77** [comment]
@si458 How do I enable translation for a new thing like this? I see it is translated. But no matter what I do, it's not translated in UI.

I tried:
Regenerate language.
Remove `translate.json` from data directory.
Restart server.
Clear cache.

Everything I do, it shill shows "No Consent" and it's not translated to my language. All translations in `translations` directory shows "No Consent" (so it seems all languages are affected).

**Comment by si458** [comment]
this is because I haven't translated any of them! I don't speak every language on the planet!
so you have to this in stages...
1. update your local `translate/translate.json` with the one from the repo
2. restart meshcentral
3. login to meshcentral as an admin account, then visit http://MYMESHSERVER.COM/translator.htm
4. now you pick ur language at the too, then search for No Consent
5. enter the correct spelling etc at the bottom
6. click save to server, then save to file, then click translate server
7. sit back, have a brew (takes about 5mins)
8. restart meshcentral
9. the pages should then all be translated with your translate.json in meshcentral-data

**Comment by exander77** [comment]
No, translation exists for me (I haven't done it):
image

And I tried to regenerate language, restart, etc. several times.

**Comment by exander77** [comment]
But these files contains "No Consent" in those selects, so something is not regenerating them:
```
translations/default-min_cs.handlebars:6821:            if (currentNode.agent.caps & 1) { x += '<div id=d2userConsentSelector>' + addHtmlValue("Souhlas uživatele", '<select id=d2userConsent style=float:right;width:250px><option value=0>' + "Pouze informovat" + '<option value=1>' + "Vyzvat k souhlasu" + '</option><option value=2>' + "No Consent" + '</option></select>') + '</div>'; }
translations/default_cs.handlebars:8274:            if (currentNode.agent.caps & 1) { x += '<div id=d2userConsentSelector>' + addHtmlValue("Souhlas uživatele", '<select id=d2userConsent style=float:right;width:250px><option value=0>' + "Pouze informovat" + '<option value=1>' + "Vyzvat k souhlasu" + '</option><option value=2>' + "No Consent" + '</option></select>') + '</div>'; }
```

**Comment by exander77** [comment]
I got it, it is a different key in translations which is not translated yet.

**Comment by si458** [comment]
Yes, this is because the phrase is "No Consent" where as the one in your picture is ", No Consent" which is used in a different place, bloody commas haha

**Comment by exander77** [comment]
> Yes, this is because the phrase is "No Consent" where as the one in your picture is ", No Consent" which is used in a different place, bloody commas haha

Yes, that totally got me. I am so stupid.

**Pull request merged**
