### PR TITLE
Pull lastconnects during lc sort

### PR DESCRIPTION
**Pull request by nzalev**
This fixes Last Seen sort updating in view1. If you have already committed/fixed, feel free to close this PR.

### CODE REVIEW

**Comment by Ylianst** [comment]
Working on a bunch of fixes in this area now. Will be done in about 15 minutes.

**Comment by nzalev** [comment]
Great. If you commit a fix, again, don't feel obligated to accept the PR.

**Comment by Ylianst** [comment]
Almost done, will look like this:

image

**Comment by Ylianst** [comment]
Finalized the sort order.... older, newer, connected, unknown.

image

**Pull request closed without merging**
